### ISSUE TITLE
Biomes not being unlocked

### ISSUE THREAD

**Issue by J4im3x0** [BentoBoxWorld/Biomes#105] opened 2022-08-21 00:06 UTC
### Expected behavior

When a player buys a biome (a biome without requirments, like level 0), the biome does not get unlocked, indeed if I ran the admin biome unlock command, does not work tho.

### Observed/Actual behavior

Maybe the check of unlock is bugged

### Steps/models to reproduce

Example biome
  pradera:
    biome: meadow
    environment: NORMAL
    name: 'Pradera'
    description: ''
    icon: cornflower
    change:
      mode: STATIC
      cost: 100

When a player buys a biome /is biomes buy llanura , the biome is not being unlocked, also I run /asadmin biomes unlock player llanuras to try unlocking, but I get the message of already unlocked, but in other hand, the player gets the message of not unlocked biome.

### BentoBox version

> bbox version
[20:02:34 INFO]: Corriendo Invalido (PUFFERFISH) 1.18.2.
[20:02:34 INFO]: Versión de BentoBox: 1.20.1
[20:02:34 INFO]: ase de datos: JSON
[20:02:34 INFO]: Mundos de juego cargados:
[20:02:34 INFO]: bskyblock_world (BSkyBlock): Mundo, Nether, End
[20:02:34 INFO]: Addons cargados:
[20:02:34 INFO]: Biomes 2.0.0 (ENABLED)
[20:02:34 INFO]: Border 3.3.0-SNAPSHOT-b136 (ENABLED)
[20:02:34 INFO]: BSkyBlock 1.15.2 (ENABLED)
[20:02:34 INFO]: Challenges 0.8.4 (ENABLED)
[20:02:34 INFO]: Chat 1.1.4 (ENABLED)
[20:02:34 INFO]: DimensionalTrees 1.6.0 (ENABLED)
[20:02:34 INFO]: ExtraMobs 1.12 (ENABLED)
[20:02:34 INFO]: IslandFly 1.8.1 (ENABLED)
[20:02:34 INFO]: Level 2.9.0 (ENABLED)
[20:02:34 INFO]: Limits 1.19.0 (ENABLED)
[20:02:34 INFO]: MACollectors-BentoBox 1.0 (ENABLED)
[20:02:34 INFO]: MagicCobblestoneGenerator 2.5.0-SNAPSHOT-b251 (ENABLED)
[20:02:34 INFO]: Visit 1.4.0 (ENABLED)
[20:02:34 INFO]: Warps 1.11.2 (ENABLED

### Plugin list

[20:06:37 INFO]: Plugins (92): AdvancedArmorStands, AdvancedCrates, AntiDonkeyDupe, AnvilColor, ArmorStandTools, BentoBox, BetterTridents, BigDoors, BlockLocker, BlockParticles, BuycraftX, CAProtect-Lite, ClearLag, CMILib, CombatLog, ConsoleSpamFix, ContainerPassthrough, CoreProtect, CustomFishing, DeluxeMenus, EpicRename, Essentials, EssentialsSpawn, EzChat*, GMusic, GSit, Harbor, HorseDupePatch, IllegalStack, Images, Jobs, LaunchPad, LeaderHeadsRevamped, LuckPerms, MA-Staff, MABot, MABukkit*, MAC*, MACollectors, MAEnd, MAGuardians, MAHolograms, MAInventories, MAKitPreview, MAParkour, MARotatingHeads, MarriageMaster, MASigns*, MASkyblock, MATab, mcMMO, MineableSpawners, MineaquaNpcs, MobFarmManager, MoneyFromMobs, Multiverse-Core, NBTAPI, NetheriteShield, OreRegenerator, PartyChatSpy*, PhantomSMP, PickMeUp, PinataParty, PlaceholderAPI, PlayerVaults, PlugMan, ProtocolLib, Quests, Rewards, Roulette, Shop, Shopkeepers, ShowItem, spark, SponsoredSlots, Sumo, TimedFly*, TitleManager, TradeSystem, TreasureChestX, TutorialCreator, Vault, ViaBackwards, ViaVersion, VoidSpawn, Votifier, WGEF-Reborn, WildTools, WorldBorderAPI, WorldEdit, WorldGuard, zAuctionHouseV3

**Comment by BONNe** [comment] 2022-08-22 10:14
The issue is with Biome "unlocking".
The unlock status is checked 2 times:
- when the player login
- when the player opens the biomes menu

Also, your biome does not require any purchase, as it is basically free. So buy command does not make any sense to use. 
However, to address this issue, I add a biome unlock status check on the "buy" command executing, so it works for you.

The issue with the admin unlock command was fixed in the dev build and it should be marked as "unlocked".

**Closed** 2022-08-22 12:04 UTC
